[package]
name = "ohos-sys"
version = "0.2.0-beta1"
edition = "2021"
description = "Bindings to the native API of OpenHarmony OS"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
