[package]
name = "ohos-sys"
version = "0.2.0-beta1"
edition = "2021"
description = "Bindings to the native API of OpenHarmony OS"
license = "Apache-2.0"
repository = "https://github.com/openharmony-rs/ohos-sys"
keywords = ["OpenHarmony", "HarmonyOS", "ffi"]

[dependencies]
document-features = { version = "0.2", optional = true }

[features]
## Enables bindings to `native_drawing`
drawing = []
## Enables bindings to `hilog`
hilog = []
## Enables bindings to `napi`
napi = []
## Enables bindings to `native_buffer`
native_buffer = []
## Enables bindings to `native_window`
native_window = []
## Enables bindings to `native_xcomponent`
xcomponent = []

#! ### OpenHarmony API level
#! This crate by default exposes bindings for API-level 10.
#! Optionally enable one of the `api-*` features to get access to bindings for newer
#! OpenHarmony versions.

## Enables bindings for OpenHarmony API-level 11
api-11 = []
## Enables bindings for OpenHarmony API-level 12
api-12 = ["api-11"]
## Document available features when building the documentation
document-features = ["dep:document-features"]

[package.metadata.docs.rs]
features = ["document-features"]
targets = ["aarch64-unknown-linux-ohos", "armv7-unknown-linux-ohos", "x86_64-unknown-linux-ohos"]